name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `master` branch.
  # If your default branch is named something else, like "master", change it here.
  push:
    branches: [ master ]
  # This line allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment.
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          # The path to your Astro project within the repository.
          # Default is the root of the repository.
          path: .
          # The version of Node.js to use.
          node-version: 20
          # The package manager to use for installing dependencies.
          package-manager: npm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4